name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./Romka04.RedirectServer/Dockerfile --tag romka04-redirect-server:$(date +%s) --tag romka04-redirect-server:latest
