name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: DockerHub Login
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_ID}}" --password-stdin

    - name: Build the Docker image
      run: docker build . -f ./Romka04.RedirectServer/Dockerfile -t romka04/redirect-server:$GITHUB_SHA --tag romka04/redirect-server:latest

  deploy:
    on:
      push:
        branches:
          - main
          
    - name: Deploy 'latest' Docker Image
      run: docker push romka04/redirect-server:latest
      
    - name: Deploy Docker Image with Commit Tag
      run: docker push romka04/redirect-server:$GITHUB_SHA

