name: Docker Image CI

on:
  push:
    branches: [ "main", "feature/git-hub-action" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      SHA: git rev-parse HEAD

    steps:
    - uses: actions/checkout@v3

    - name: Echo SHA Local Variable
      run: echo $SHA
      
    - name: DockerHub Login
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_ID}}" --password-stdin

    - name: Build the Docker image
      run: docker build . -f ./Romka04.RedirectServer/Dockerfile -t romka04/redirect-server:$(SHA) --tag romka04/redirect-server:latest

    - name: Deploy 'latest' Docker Image
      run: docker push romka04/redirect-server:latest
      
    - name: Deploy Docker Image with Commit Tag
      run: docker push romka04/redirect-server:$(SHA)

